/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Note = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Vec(Note),
  'severity' : Severity,
  'reporter' : IDL.Principal,
  'assignedAnalyst' : IDL.Opt(IDL.Principal),
});
export const IncidentType = IDL.Variant({
  'dataBreach' : IDL.Null,
  'unauthorizedAccess' : IDL.Null,
  'other' : IDL.Null,
  'ddos' : IDL.Null,
  'phishing' : IDL.Null,
  'malware' : IDL.Null,
});
export const IncidentReport = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkedCaseId' : IDL.Nat,
  'reporterName' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'affectedSystems' : IDL.Text,
  'severity' : Severity,
  'incidentType' : IncidentType,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'analyst' : IDL.Null });
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNoteToCase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCase' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCase' : IDL.Func([IDL.Text, IDL.Text, Severity], [IDL.Nat], []),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllIncidentReports' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseById' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
  'getIncidentReportById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IncidentReport)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, Role], [], []),
  'submitIncidentReport' : IDL.Func(
      [IDL.Text, IncidentType, IDL.Text, IDL.Text, Severity, IDL.Text],
      [IDL.Nat, IDL.Nat],
      [],
    ),
  'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Note = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Vec(Note),
    'severity' : Severity,
    'reporter' : IDL.Principal,
    'assignedAnalyst' : IDL.Opt(IDL.Principal),
  });
  const IncidentType = IDL.Variant({
    'dataBreach' : IDL.Null,
    'unauthorizedAccess' : IDL.Null,
    'other' : IDL.Null,
    'ddos' : IDL.Null,
    'phishing' : IDL.Null,
    'malware' : IDL.Null,
  });
  const IncidentReport = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkedCaseId' : IDL.Nat,
    'reporterName' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'affectedSystems' : IDL.Text,
    'severity' : Severity,
    'incidentType' : IncidentType,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'analyst' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNoteToCase' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCase' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCase' : IDL.Func([IDL.Text, IDL.Text, Severity], [IDL.Nat], []),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllIncidentReports' : IDL.Func(
        [],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseById' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
    'getIncidentReportById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IncidentReport)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [], []),
    'submitIncidentReport' : IDL.Func(
        [IDL.Text, IncidentType, IDL.Text, IDL.Text, Severity, IDL.Text],
        [IDL.Nat, IDL.Nat],
        [],
      ),
    'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };