/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Case {
  'id' : bigint,
  'status' : CaseStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'notes' : Array<Note>,
  'severity' : Severity,
  'reporter' : Principal,
  'assignedAnalyst' : [] | [Principal],
}
export type CaseStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface IncidentReport {
  'id' : bigint,
  'title' : string,
  'linkedCaseId' : bigint,
  'reporterName' : string,
  'createdAt' : bigint,
  'description' : string,
  'affectedSystems' : string,
  'severity' : Severity,
  'incidentType' : IncidentType,
}
export type IncidentType = { 'dataBreach' : null } |
  { 'unauthorizedAccess' : null } |
  { 'other' : null } |
  { 'ddos' : null } |
  { 'phishing' : null } |
  { 'malware' : null };
export interface Note {
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export type Role = { 'admin' : null } |
  { 'analyst' : null };
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNoteToCase' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCase' : ActorMethod<[bigint, Principal], undefined>,
  'createCase' : ActorMethod<[string, string, Severity], bigint>,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getAllIncidentReports' : ActorMethod<[], Array<IncidentReport>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseById' : ActorMethod<[bigint], [] | [Case]>,
  'getIncidentReportById' : ActorMethod<[bigint], [] | [IncidentReport]>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[Principal, Role], undefined>,
  'submitIncidentReport' : ActorMethod<
    [string, IncidentType, string, string, Severity, string],
    [bigint, bigint]
  >,
  'updateCaseStatus' : ActorMethod<[bigint, CaseStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];